import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { LayoutGrid, Search, X, Download } from 'lucide-react';
import FormModal from '../components/FormModal';
import BusShape from '../components/whiteboard/BusShape';

const exportBoard = (buses, filters) => {
  const rows = buses.map(b => {
    const status = b.board_status || 'Available';
    const m = STATUS_META[status] || STATUS_META['Available'];
    const isSubAvail = (b.route_class || 'Permanent') === 'Substitute' && status === 'Available';
    const bg = isSubAvail ? 'hsl(330,80%,55%)' : m.bg;
    return `<tr>
      <td style="text-align:center;font-weight:700;font-size:13px">${b.bus_number || ''}</td>
      <td>${b.bus_type || ''}</td>
      <td>${b.base_location || ''}</td>
      <td>${b.route_class || 'Permanent'}</td>
      <td style="text-align:center"><span style="background:${bg};color:${isSubAvail?'white':m.text};padding:2px 10px;border-radius:3px;font-size:11px;font-weight:700;letter-spacing:0.05em">${isSubAvail?'SUB — AVAIL':m.label}</span></td>
      <td>${b.make || ''} ${b.model || ''}</td>
    </tr>`;
  }).join('');

  const filterLine = [
    filters.lot !== 'All' ? `Lot: ${filters.lot}` : null,
    filters.type !== 'All' ? `Type: ${filters.type}` : null,
    filters.routeClass !== 'All' ? `Route: ${filters.routeClass}` : null,
    filters.search ? `Search: "${filters.search}"` : null,
  ].filter(Boolean).join(' &nbsp;|&nbsp; ');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>White Board Export</title>
<style>
  body { font-family: 'Courier New', monospace; padding: 20px; color: #1a1a1a; }
  h1 { font-size: 16px; letter-spacing: 0.08em; margin: 0 0 4px; }
  .sub { font-size: 11px; color: #555; margin-bottom: 4px; }
  .filters { font-size: 10px; color: #444; background: #eee; border: 1px solid #ccc; padding: 4px 8px; margin-bottom: 12px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { background: hsl(220,50%,30%); color: white; padding: 6px 8px; text-align: left; font-size: 10px; letter-spacing: 0.06em; }
  td { padding: 5px 8px; border-bottom: 1px solid #ddd; }
  tr:nth-child(even) { background: #f7f7f7; }
  .foot { margin-top: 10px; font-size: 9px; color: #888; }
</style></head><body>
  <h1>WHITE BOARD — BUS STATUS EXPORT</h1>
  <div class="sub">NHCS Transportation — Data-TraCs System &nbsp;|&nbsp; ${new Date().toLocaleString()}</div>
  ${filterLine ? `<div class="filters"><strong>FILTERS:</strong> ${filterLine}</div>` : ''}
  <table>
    <thead><tr><th>BUS #</th><th>TYPE</th><th>LOT</th><th>ROUTE</th><th>STATUS</th><th>MAKE / MODEL</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="foot">Total buses: ${buses.length} &nbsp;|&nbsp; Generated by White Board Export</div>
</body></html>`;

  const w = window.open('', '_blank');
  if (w) { w.document.write(html); w.document.close(); }
};

const FF = "'Courier Prime', monospace";

const STATUS_META = {
  'Available':  { label: 'AVAILABLE',  bg: 'hsl(140,60%,45%)',  border: 'hsl(140,60%,32%)', text: 'white',  glow: '0 0 10px hsl(140,60%,45%)' },
  'Dead Line':  { label: 'DEAD LINE',  bg: 'hsl(0,70%,50%)',    border: 'hsl(0,70%,38%)',   text: 'white',  glow: '0 0 10px hsl(0,70%,50%)' },
  'MI':         { label: 'MI',         bg: 'hsl(210,70%,50%)',  border: 'hsl(210,70%,38%)', text: 'white',  glow: '0 0 10px hsl(210,70%,50%)' },
  'PM':         { label: 'PM',         bg: 'hsl(45,90%,50%)',   border: 'hsl(45,90%,38%)',  text: '#1a1a1a', glow: '0 0 10px hsl(45,90%,50%)' },
  'Active Trip': { label: 'ACTIVE TRIP', bg: 'hsl(280,55%,48%)', border: 'hsl(280,55%,36%)', text: 'white', glow: '0 0 10px hsl(280,55%,48%)' },
  'Parked OOS': { label: 'PARKED OOS', bg: 'hsl(220,8%,45%)', border: 'hsl(220,10%,32%)', text: 'white', glow: '0 0 8px hsl(220,8%,40%)' },
};

const STATUS_ORDER = ['Available', 'Dead Line', 'MI', 'PM', 'Active Trip', 'Parked OOS'];

export default function WhiteBoard() {
  const queryClient = useQueryClient();
  const [lotFilter, setLotFilter] = useState('All');
  const [typeFilter, setTypeFilter] = useState('All');
  const [routeClassFilter, setRouteClassFilter] = useState('All');
  const [search, setSearch] = useState('');
  const [selectedBus, setSelectedBus] = useState(null);

  const { data: buses = [], isLoading } = useQuery({
    queryKey: ['buses'],
    queryFn: () => base44.entities.Bus.list('bus_number'),
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, board_status }) => base44.entities.Bus.update(id, { board_status }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['buses'] }),
  });

  const activeBuses = buses.filter(b => b.status !== 'Retired' && b.base_location !== 'Sold' && b.whiteboard_tracking !== false && (b.bus_number || '').toUpperCase() !== 'LAB HOURS');

  const filtered = activeBuses.filter(b => {
    const lotMatch = lotFilter === 'All' || b.base_location === lotFilter;
    const typeMatch = typeFilter === 'All' || b.bus_type === typeFilter;
    const routeClassMatch = routeClassFilter === 'All' || (b.route_class || 'Permanent') === routeClassFilter;
    const q = search.toLowerCase();
    const searchMatch = !search || b.bus_number?.toLowerCase().includes(q) || b.make?.toLowerCase().includes(q) || b.model?.toLowerCase().includes(q);
    return lotMatch && typeMatch && routeClassMatch && searchMatch;
  });

  const counts = STATUS_ORDER.reduce((acc, s) => {
    acc[s] = activeBuses.filter(b => (b.board_status || 'Available') === s).length;
    return acc;
  }, {});

  const handleSetStatus = (status) => {
    if (!selectedBus) return;
    updateMutation.mutate({ id: selectedBus.id, board_status: status });
    setSelectedBus(null);
  };

  const btnBase = { padding: '3px 8px', fontSize: '10px', fontFamily: FF, fontWeight: '700', border: '1px solid', borderRadius: '2px', cursor: 'pointer' };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', fontFamily: FF }}>
      {/* Header */}
      <div style={{ background: 'linear-gradient(to right, hsl(220,50%,30%), hsl(220,45%,40%))', color: 'white', padding: '10px 14px', borderRadius: '2px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '8px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <LayoutGrid style={{ width: 20, height: 20 }} />
          <div>
            <div style={{ fontSize: '13px', fontWeight: '700', letterSpacing: '0.08em' }}>WHITE BOARD — BUS STATUS BOARD</div>
            <div style={{ fontSize: '10px', opacity: 0.8, letterSpacing: '0.05em' }}>REAL-TIME FLEET AVAILABILITY — CLICK A BUS TO CHANGE STATUS</div>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
          <Search style={{ width: 12, height: 12, color: 'rgba(255,255,255,0.7)' }} />
          <input
            placeholder="Search bus #, make, model..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            style={{ padding: '4px 8px', fontSize: '11px', fontFamily: FF, border: '1px solid rgba(255,255,255,0.3)', borderRadius: '2px', background: 'rgba(255,255,255,0.15)', color: 'white', width: '220px', outline: 'none' }}
          />
        </div>
      </div>

      {/* Legend / Stats */}
      <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
        {STATUS_ORDER.map(s => {
          const m = STATUS_META[s];
          return (
            <div key={s} style={{ background: 'white', border: `1px solid hsl(220,18%,78%)`, borderLeft: `4px solid ${m.bg}`, borderRadius: '2px', padding: '8px 12px', flex: '1', minWidth: '120px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                <span style={{ display: 'inline-block', width: '12px', height: '12px', background: m.bg, border: `1px solid ${m.border}`, borderRadius: '2px' }} />
                <span style={{ fontSize: '9px', fontWeight: '700', color: 'hsl(220,20%,35%)', letterSpacing: '0.06em' }}>{m.label}</span>
              </div>
              <div style={{ fontSize: '20px', fontWeight: '700', color: m.bg, lineHeight: 1, marginTop: '4px' }}>{counts[s]}</div>
            </div>
          );
        })}
      </div>

      {/* Lot Filter */}
      <div style={{ background: 'hsl(220,18%,96%)', border: '1px solid hsl(220,18%,78%)', borderRadius: '2px', padding: '6px 10px', display: 'flex', alignItems: 'center', gap: '5px', flexWrap: 'wrap' }}>
        <span style={{ fontSize: '10px', fontWeight: '700', color: 'hsl(220,20%,35%)', letterSpacing: '0.06em' }}>LOT:</span>
        {['All', 'Main', 'North'].map(l => (
          <button key={l} onClick={() => setLotFilter(l)} style={{ ...btnBase, background: lotFilter === l ? 'hsl(220,55%,38%)' : 'white', color: lotFilter === l ? 'white' : 'hsl(220,20%,30%)', borderColor: lotFilter === l ? 'hsl(220,55%,38%)' : 'hsl(220,18%,72%)' }}>
            {l.toUpperCase()}
          </button>
        ))}
        <span style={{ fontSize: '10px', fontWeight: '700', color: 'hsl(220,20%,35%)', letterSpacing: '0.06em', marginLeft: '8px' }}>TYPE:</span>
        {['All', 'School Bus', 'Activity Bus'].map(t => (
          <button key={t} onClick={() => setTypeFilter(t)} style={{ ...btnBase, background: typeFilter === t ? 'hsl(220,55%,38%)' : 'white', color: typeFilter === t ? 'white' : 'hsl(220,20%,30%)', borderColor: typeFilter === t ? 'hsl(220,55%,38%)' : 'hsl(220,18%,72%)' }}>
            {t === 'All' ? 'ALL' : t.toUpperCase()}
          </button>
        ))}
        <span style={{ fontSize: '10px', fontWeight: '700', color: 'hsl(220,20%,35%)', letterSpacing: '0.06em', marginLeft: '8px' }}>ROUTE:</span>
        {['All', 'Permanent', 'Substitute'].map(r => (
          <button key={r} onClick={() => setRouteClassFilter(r)} style={{ ...btnBase, background: routeClassFilter === r ? (r === 'Substitute' ? 'hsl(330,80%,52%)' : 'hsl(220,55%,38%)') : 'white', color: routeClassFilter === r ? 'white' : 'hsl(220,20%,30%)', borderColor: routeClassFilter === r ? (r === 'Substitute' ? 'hsl(330,80%,42%)' : 'hsl(220,55%,38%)') : 'hsl(220,18%,72%)' }}>
            {r === 'All' ? 'ALL' : r === 'Substitute' ? 'SUBSTITUTE' : 'PERMANENT'}
          </button>
        ))}
        <span style={{ fontSize: '10px', color: 'hsl(220,10%,50%)', marginLeft: 'auto' }}>SHOWING {filtered.length} BUSES</span>
        <button onClick={() => exportBoard(filtered, { lot: lotFilter, type: typeFilter, routeClass: routeClassFilter, search })} style={{ ...btnBase, background: 'hsl(220,55%,38%)', color: 'white', borderColor: 'hsl(220,55%,28%)', display: 'inline-flex', alignItems: 'center', gap: '4px' }}>
          <Download style={{ width: 11, height: 11 }} /> EXPORT BOARD
        </button>
      </div>

      {/* Board */}
      {isLoading ? (
        <div style={{ padding: '40px', textAlign: 'center', fontFamily: FF, color: 'hsl(220,10%,45%)', fontSize: '12px' }}>LOADING FLEET...</div>
      ) : filtered.length === 0 ? (
        <div style={{ padding: '40px', textAlign: 'center', fontFamily: FF, color: 'hsl(220,10%,45%)', fontSize: '12px' }}>NO BUSES MATCH FILTER</div>
      ) : (
        <div style={{ background: 'hsl(220,18%,96%)', border: '1px solid hsl(220,18%,78%)', borderRadius: '2px', padding: '10px' }}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(110px, 1fr))', gap: '8px' }}>
            {filtered.map(b => {
              const status = b.board_status || 'Available';
              const m = STATUS_META[status];
              const isSubAvail = (b.route_class || 'Permanent') === 'Substitute' && status === 'Available';
              const bg = isSubAvail ? 'hsl(330,80%,55%)' : m.bg;
              const border = isSubAvail ? 'hsl(330,80%,42%)' : m.border;
              const text = isSubAvail ? 'white' : m.text;
              const glow = isSubAvail ? '0 0 10px hsl(330,80%,60%)' : m.glow;
              return (
                <button
                  key={b.id}
                  onClick={() => setSelectedBus(b)}
                  style={{
                    background: 'transparent', border: 'none', padding: '4px 4px 10px', cursor: 'pointer', fontFamily: FF,
                    display: 'flex', flexDirection: 'column', alignItems: 'center',
                    boxShadow: 'none', transition: 'transform 0.1s', minHeight: '0',
                    position: 'relative',
                  }}
                  onMouseEnter={e => { e.currentTarget.style.transform = 'scale(1.06)'; }}
                  onMouseLeave={e => { e.currentTarget.style.transform = 'scale(1)'; }}
                >
                  <BusShape
                    busNumber={b.bus_number}
                    statusLabel={isSubAvail ? 'SUB — AVAIL' : m.label}
                    bg={bg}
                    border={border}
                    text={text}
                    isSub={isSubAvail}
                    make={b.make}
                    glow={glow}
                  />
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* Status picker modal */}
      <FormModal open={!!selectedBus} onClose={() => setSelectedBus(null)} maxWidth="420px">
        {selectedBus && (
          <div style={{ background: 'white', borderRadius: '2px', fontFamily: FF }}>
            <div style={{ background: 'linear-gradient(to right, hsl(220,50%,30%), hsl(220,45%,40%))', color: 'white', padding: '8px 12px', fontSize: '12px', fontWeight: '700', letterSpacing: '0.08em', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span>BUS #{selectedBus.bus_number} — SET STATUS</span>
              <button onClick={() => setSelectedBus(null)} style={{ background: 'none', border: 'none', color: 'white', cursor: 'pointer' }}><X style={{ width: 14, height: 14 }} /></button>
            </div>
            <div style={{ padding: '14px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <div style={{ fontSize: '10px', color: 'hsl(220,10%,45%)' }}>
                Current: <strong style={{ color: STATUS_META[selectedBus.board_status || 'Available'].bg }}>{STATUS_META[selectedBus.board_status || 'Available'].label}</strong>
                {selectedBus.make ? ` — ${selectedBus.make} ${selectedBus.model || ''}`.trim() : ''}
              </div>
              {STATUS_ORDER.map(s => {
                const m = STATUS_META[s];
                const isCurrent = (selectedBus.board_status || 'Available') === s;
                return (
                  <button
                    key={s}
                    onClick={() => handleSetStatus(s)}
                    disabled={isCurrent}
                    style={{
                      background: m.bg, color: m.text, border: `2px solid ${m.border}`, borderRadius: '4px',
                      padding: '12px', fontFamily: FF, fontSize: '13px', fontWeight: '700', letterSpacing: '0.08em',
                      cursor: isCurrent ? 'default' : 'pointer', opacity: isCurrent ? 0.55 : 1,
                      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                    }}
                  >
                    <span>● {m.label}</span>
                    {isCurrent && <span style={{ fontSize: '9px', opacity: 0.8 }}>CURRENT</span>}
                  </button>
                );
              })}
            </div>
          </div>
        )}
      </FormModal>
    </div>
  );
}